#!/bin/bash
gnome-terminal --tab --title="step 1 roscore" -e "bash -c \"; exec bash\"";
sleep 3
gnome-terminal --tab --title="step 2 minimal" -e "bash -c \"roslaunch turtlebot_bringup minimal.launch; exec bash\"";
sleep 4;

gnome-terminal --tab --title="step 3 astra_pro" -e "bash -c \"roslaunch astra_launch astra_pro.launch; exec bash\"";
sleep 4;
gnome-terminal --tab --title="step 4 cmvision" -e "bash -c \"source /opt/ros/indigo/setup.sh;cd /home/turtlebot/turtlebot_ws/src/cmvision;roslaunch cmvision cmvision.launch image:=/camera/rgb/image_raw; exec bash;\"";

