// Generated by gencpp from file cmvision_3d/Blobs3d.msg
// DO NOT EDIT!


#ifndef CMVISION_3D_MESSAGE_BLOBS3D_H
#define CMVISION_3D_MESSAGE_BLOBS3D_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <cmvision_3d/Blob3d.h>

namespace cmvision_3d
{
template <class ContainerAllocator>
struct Blobs3d_
{
  typedef Blobs3d_<ContainerAllocator> Type;

  Blobs3d_()
    : header()
    , blob_count(0)
    , blobs()  {
    }
  Blobs3d_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , blob_count(0)
    , blobs(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint32_t _blob_count_type;
  _blob_count_type blob_count;

   typedef std::vector< ::cmvision_3d::Blob3d_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::cmvision_3d::Blob3d_<ContainerAllocator> >::other >  _blobs_type;
  _blobs_type blobs;




  typedef boost::shared_ptr< ::cmvision_3d::Blobs3d_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cmvision_3d::Blobs3d_<ContainerAllocator> const> ConstPtr;

}; // struct Blobs3d_

typedef ::cmvision_3d::Blobs3d_<std::allocator<void> > Blobs3d;

typedef boost::shared_ptr< ::cmvision_3d::Blobs3d > Blobs3dPtr;
typedef boost::shared_ptr< ::cmvision_3d::Blobs3d const> Blobs3dConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cmvision_3d::Blobs3d_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cmvision_3d::Blobs3d_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace cmvision_3d

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'cmvision_3d': ['/home/turtlebot/turtlebot_ws/src/cmvision_3d/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::cmvision_3d::Blobs3d_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cmvision_3d::Blobs3d_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cmvision_3d::Blobs3d_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cmvision_3d::Blobs3d_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cmvision_3d::Blobs3d_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cmvision_3d::Blobs3d_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cmvision_3d::Blobs3d_<ContainerAllocator> >
{
  static const char* value()
  {
    return "869bbddc0459864dc4de06329dfb061b";
  }

  static const char* value(const ::cmvision_3d::Blobs3d_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x869bbddc0459864dULL;
  static const uint64_t static_value2 = 0xc4de06329dfb061bULL;
};

template<class ContainerAllocator>
struct DataType< ::cmvision_3d::Blobs3d_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cmvision_3d/Blobs3d";
  }

  static const char* value(const ::cmvision_3d::Blobs3d_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cmvision_3d::Blobs3d_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
uint32 blob_count\n\
Blob3d[] blobs\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: cmvision_3d/Blob3d\n\
string name\n\
uint32 red\n\
uint32 green\n\
uint32 blue\n\
uint32 area\n\
geometry_msgs/Point center\n\
geometry_msgs/Point top_left\n\
geometry_msgs/Point bottom_right\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::cmvision_3d::Blobs3d_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cmvision_3d::Blobs3d_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.blob_count);
      stream.next(m.blobs);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Blobs3d_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cmvision_3d::Blobs3d_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cmvision_3d::Blobs3d_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "blob_count: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.blob_count);
    s << indent << "blobs[]" << std::endl;
    for (size_t i = 0; i < v.blobs.size(); ++i)
    {
      s << indent << "  blobs[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::cmvision_3d::Blob3d_<ContainerAllocator> >::stream(s, indent + "    ", v.blobs[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // CMVISION_3D_MESSAGE_BLOBS3D_H
